In [1]:
import numpy as np

#### Shape of Matrix

In [2]:
# Creating a matrix
m1 = np.array([[2,3],[6,7]])
m1

array([[2, 3],
       [6, 7]])

In [3]:
m1.shape

(2, 2)

In [4]:
m2 = np.array([[10,25,45],[50,64,80],[20,15,90]])
m2

array([[10, 25, 45],
       [50, 64, 80],
       [20, 15, 90]])

In [5]:
m2.shape

(3, 3)

#### Matrix with random values

In [6]:
rm = np.random.rand(3,3)
rm

array([[0.72861141, 0.81117331, 0.71062667],
       [0.3785715 , 0.70949384, 0.96501654],
       [0.46350777, 0.3895567 , 0.18170197]])

In [9]:
rmi = np.random.randint(100,size=(3,3))
rmi

array([[ 4,  7, 69],
       [50, 89, 96],
       [63, 65, 41]])

#### Transpose of a Matrix

In [10]:
a = np.random.randint(100,size=(2,4))

In [11]:
np.transpose(a)

array([[ 0, 57],
       [87, 22],
       [99, 94],
       [30, 76]])

### Matrix Operations
- Addition
- Subtration
- Multiply with scalar
- Multiplication of 2 matrices