#### Write a program to find i

In [5]:
import numpy as np

#### Write a program to work with matrix 


In [3]:
mat = [[1,2],[3,4]]
mat

[[1, 2], [3, 4]]

In [6]:
v1 = np.array([1,-1,2])
v2 = np.array([2,5,2])

In [7]:
print(v1,v2)

[ 1 -1  2] [2 5 2]


In [8]:
# Algebra of Vectors
print(v1+v2)
print(v1-v2)
print(v1*3)

[3 4 4]
[-1 -6  0]
[ 3 -3  6]


In [10]:
print(np.linalg.norm(v1))  # Magnitude of vectors

2.449489742783178


In [11]:
print(np.dot(v1,v2))

1
