In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

print(a1,a2,a3)

[1 2 3] [[1 2 3]
 [4 5 6]] [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional, 2-dimensional, 3-dimensional array 
# (shape, number of dimensions, data type, size and type)
print(
a1.shape,
a1.ndim,
a1.dtype,
a1.size,
type(a1))

(3,) 1 int32 3 <class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

pd.DataFrame(a2)
# pd.DataFrame(a3)

# Data Frame can be created only of 1-d or 2-d array

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
val_array = np.arange(0,100,3)
val_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10,size=(7,2))
random_array

array([[1, 0],
       [4, 6],
       [1, 5],
       [0, 4],
       [9, 4],
       [2, 9],
       [2, 9]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random((3,5))
random_float_array

array([[0.0355301 , 0.68315137, 0.66655395, 0.36955998, 0.82431479],
       [0.62184812, 0.49619802, 0.1769187 , 0.86646759, 0.08558221],
       [0.71507695, 0.52069182, 0.42279247, 0.62145419, 0.5389253 ]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
r_array = np.random.randint(10,size=(4,6))
r_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [55]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ar = np.random.randint(1,10,size=(3,7))
print(ar)

# Find the unique numbers in the array you just created
np.unique(ar)

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]
 [1 3 5 3 1 5 7]]


array([1, 2, 3, 5, 6, 7, 8, 9])

In [56]:
# Find the 0'th index of the latest array you created
ar[0][0]

9

In [57]:
# Get the first 2 rows of latest array you created
ar[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [59]:
# Get the first 2 values of the first 2 rows of the latest array
ar[:2,:2]

array([[9, 7],
       [7, 8]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar1 = np.random.randint(1,10,size=(3,5))
ar2 = np.ones((3,5))

In [62]:
print(ar1)
print(ar2)

[[7 9 3 7 1]
 [4 4 5 7 7]
 [4 7 3 6 2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# Add the two arrays together
ar4 = np.add(ar1,ar2)

In [64]:
# Create another array of ones of shape (5, 3)
ar3 = np.ones((5,3))

In [67]:
# Try add the array of ones and the other most recent array together
np.add(ar3,ar4)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [68]:
# Create another array of ones of shape (3, 5)
ar3 = np.ones((3,5))

In [69]:
# Subtract the new array of ones from the other most recent array
np.subtract(ar4,ar3)

array([[7., 9., 3., 7., 1.],
       [4., 4., 5., 7., 7.],
       [4., 7., 3., 6., 2.]])

In [70]:
# Multiply the ones array with the latest array
np.multiply(ar3,ar4)

array([[ 8., 10.,  4.,  8.,  2.],
       [ 5.,  5.,  6.,  8.,  8.],
       [ 5.,  8.,  4.,  7.,  3.]])

In [71]:
# Take the latest array to the power of 2 using '**'
np.array(ar4**2)

array([[ 64., 100.,  16.,  64.,   4.],
       [ 25.,  25.,  36.,  64.,  64.],
       [ 25.,  64.,  16.,  49.,   9.]])

In [72]:
# Do the same thing with np.square()
np.square(ar4)

array([[ 64., 100.,  16.,  64.,   4.],
       [ 25.,  25.,  36.,  64.,  64.],
       [ 25.,  64.,  16.,  49.,   9.]])

In [73]:
# Find the mean of the latest array using np.mean()
np.mean(ar4)

6.066666666666666

In [74]:
# Find the maximum of the latest array using np.max()
np.max(ar4)

10.0

In [75]:
# Find the minimum of the latest array using np.min()
np.min(ar4)

2.0

In [76]:
# Find the standard deviation of the latest array
np.std(ar4)

2.2050447211388304

In [77]:
# Find the variance of the latest array
np.var(ar4)

4.862222222222223

In [78]:
# Reshape the latest array to (3, 5, 1)
np.reshape(ar4,(3,5,1))

array([[[ 8.],
        [10.],
        [ 4.],
        [ 8.],
        [ 2.]],

       [[ 5.],
        [ 5.],
        [ 6.],
        [ 8.],
        [ 8.]],

       [[ 5.],
        [ 8.],
        [ 4.],
        [ 7.],
        [ 3.]]])

In [79]:
# Transpose the latest array
np.transpose(ar4)

array([[ 8.,  5.,  5.],
       [10.,  5.,  8.],
       [ 4.,  6.,  4.],
       [ 8.,  8.,  7.],
       [ 2.,  8.,  3.]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar5 = np.random.randint(10,size=(3,3))
ar6 = np.random.random((3,2))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(ar5,ar6)

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar7 = np.random.randint(10,size=(4,3))
ar8 = np.random.randint(10,size=(4,3))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(ar7,ar8)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.transpose(ar7)

array([[9, 5, 6, 0],
       [8, 3, 8, 0],
       [4, 9, 6, 8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [84]:
# Compare the two arrays with '>'
ar7 > ar8

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [85]:
# Compare the two arrays with '>='
ar7 >= ar8

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True],
       [ True, False, False]])

In [86]:
# Find which elements of the first array are greater than 7
ar7 > 7

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [87]:
# Which parts of each array are equal? (try using '==')
ar7 == ar8

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [88]:
# Sort one of the arrays you just created in ascending order
np.sort(ar7)

array([[4, 8, 9],
       [3, 5, 9],
       [6, 6, 8],
       [0, 0, 8]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar7)

array([[2, 1, 0],
       [1, 0, 2],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar7)

0

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar7)

9

In [92]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar7,axis=1)

array([0, 2, 1, 2], dtype=int64)

In [93]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar7,axis=1)

array([2, 1, 0, 0], dtype=int64)